using Microsoft.WindowsAzure.Storage.Table;
using System;

namespace HoloLens4Labs.Scripts.DTOs
{
    /// <summary>
    /// Experiment DTO for transfering experiments to the Azure Table service
    /// </summary>
    public class ExperimentDTO : TableEntity
    {
        /// <summary>
        /// The name of the experiment    
        /// </summary>
        public string Name { get; set; }
        
        /// <summary>
        /// The ID of the scientist who created the experiment
        /// </summary>
        public DateTime DateTime { get; set; }

        /// <summary>
        /// The ID of the of the experiment as generated by the app
        /// </summary>
        public string ExperimentID { get; set; }

        /// <summary>
        /// The ID of the scientist who created the experiment
        /// </summary>
        public string ScientistsID { get; set; }

    }
}
